spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1
    url: jdbc:postgresql://localhost:5432/springproject
    username: postgres

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

  main:
    allow-bean-definition-overriding: true

redis:
  host: localhost
  port: 6379
  timeout: 60000
remote:
  url: http://44c0-5-219-91-210.ngrok.io

